using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Anka.Routing.Generator;

[Generator]
public sealed class RouteGenerator : IIncrementalGenerator
{
    private const string RouteAttribute = "Anka.Routing.RouteAttribute";
    private const string HandlerInterface = "Anka.Routing.IRouteHandler";

    private static readonly DiagnosticDescriptor NotAHandler = new(
        "ANKA001", "Route target is not a handler",
        "'{0}' has [Route] but does not implement IRouteHandler",
        "Anka.Routing", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NoParameterlessCtor = new(
        "ANKA002", "Handler needs a public parameterless constructor",
        "'{0}' must have a public parameterless constructor to be registered",
        "Anka.Routing", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateRoute = new(
        "ANKA003", "Duplicate route",
        "Route '{0}' is declared by both '{1}' and '{2}'",
        "Anka.Routing", DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1) Only classes carrying [Route] — Roslyn filters by attribute name before we see anything.
        var routes = context.SyntaxProvider.ForAttributeWithMetadataName(
            RouteAttribute,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => ToModel(ctx));

        // 2) Collect into one list; RouteModel is a record, so unchanged input means cached output.
        context.RegisterSourceOutput(routes.Collect(), static (spc, models) => Emit(spc, models));
    }

    private static RouteModel ToModel(GeneratorAttributeSyntaxContext ctx)
    {
        var type = (INamedTypeSymbol)ctx.TargetSymbol;
        var path = ctx.Attributes[0].ConstructorArguments[0].Value as string ?? "";
        var implementsHandler = type.AllInterfaces.Any(i => i.ToDisplayString() == HandlerInterface);
        var hasCtor = type.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);
        var location = ctx.TargetNode.GetLocation();

        return new RouteModel(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            type.Name,
            path,
            implementsHandler,
            hasCtor,
            location.SourceTree?.FilePath ?? "",
            location.SourceSpan,
            location.GetLineSpan().Span);
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<RouteModel> models)
    {
        var valid = ImmutableArray.CreateBuilder<RouteModel>();
        foreach (var m in models)
        {
            if (!m.ImplementsHandler)
            {
                spc.ReportDiagnostic(Diagnostic.Create(NotAHandler, m.Location, m.Name));
                continue;
            }

            if (!m.HasParameterlessCtor)
            {
                spc.ReportDiagnostic(Diagnostic.Create(NoParameterlessCtor, m.Location, m.Name));
                continue;
            }

            var existing = valid.FirstOrDefault(v => v.Path == m.Path);
            if (existing is not null)
            {
                spc.ReportDiagnostic(Diagnostic.Create(DuplicateRoute, m.Location, m.Path, existing.Name, m.Name));
                continue;
            }

            valid.Add(m);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Anka.Routing.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class RouteTable");
        sb.AppendLine("{");

        for (var i = 0; i < valid.Count; i++)
        {
            sb.AppendLine($"    private static readonly {valid[i].FullName} s_h{i} = new();");
        }

        sb.AppendLine();
        sb.AppendLine($"    public const int Count = {valid.Count};");
        sb.AppendLine();
        sb.AppendLine("    public static bool TryDispatch(global::Anka.HttpRequest request, global::Anka.HttpResponseWriter response,");
        sb.AppendLine("                                   global::System.Threading.CancellationToken ct, out global::System.Threading.Tasks.ValueTask task)");
        sb.AppendLine("    {");
        sb.AppendLine("        var path = request.PathBytes;");
        sb.AppendLine("        switch (path.Length)");
        sb.AppendLine("        {");

        // Group by byte length first — same idea as Anka's HttpMethodParser.
        foreach (var group in valid.Select((m, i) => (m, i)).GroupBy(x => Encoding.UTF8.GetByteCount(x.m.Path)).OrderBy(g => g.Key))
        {
            sb.AppendLine($"            case {group.Key}:");
            foreach (var (m, i) in group)
            {
                sb.AppendLine($"                if (path.SequenceEqual(\"{Escape(m.Path)}\"u8)) {{ task = s_h{i}.HandleAsync(request, response, ct); return true; }}");
            }
            sb.AppendLine("                break;");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        task = default;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("RouteTable.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}

internal sealed record RouteModel(
    string FullName,
    string Name,
    string Path,
    bool ImplementsHandler,
    bool HasParameterlessCtor,
    string FilePath,
    TextSpan Span,
    LinePositionSpan LineSpan)
{
    public Location Location => Location.Create(FilePath, Span, LineSpan);
}
